name: Build and Run Middleware

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Build Middleware
        run: |
          cd middleware
          go build

      - name: Run Middleware
        run: |
          cd middleware
          ./middleware &
